name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install && npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Adjust to your Laravel PHP version

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # Adjust this to your server directory
          local-dir: ./ # Adjust this to your local directory if needed
          protocol: ftps
